---
# file: roles/go/tasks/macosx/main.yml

- name: install ports
  macports:
    name="{{ item }}"
    state=present
  sudo: yes
  with_items:
    - go
    - go-tools

- name: setup GOPATH
  file:
    path="{{ go_path }}"
    state=directory
    mode=0755 group='staff'
